apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cicd-demo
        version: production
    spec:
      imagePullSecrets:
      - name: demo-registry-secret
      containers:
      - name: demo
        image: repository.parkingwang.com/demo/cicd-demo-<BRANCH_NAME>:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 80m
            memory: 80Mi
          requests:
            cpu: 20m
            memory: 20Mi 
        ports:
        - name: web
          containerPort: 8801


