apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cicd-destinationrule
spec:
  host: cicd-demo-svc
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: cicd-demo-v1
      labels:
        version: v1
    - name: cicd-demo-v2
      labels:
        version: v2
    - name: cicd-demo-test
      labels:
        version: test