apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cicd-demo-ingress
  namespace: istio-system # 这里用了broker 必须与istio命名空间一致
  labels:
    app: cicd-demo-ingress
spec:
  rules:
  - host: cicd-demo.rustc.io
    http:
      paths:
      - path: /
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80